# Generated by Django 6.0.8 on 2026-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
